name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]  # 可以根据需要修改触发分支
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.cn-shenzhen.aliyuncs.com  # 替换为你的阿里云仓库地址
        username: ${{ secrets.ALIYUN_USERNAME }}  # 阿里云账号
        password: ${{ secrets.ALIYUN_PASSWORD }}  # 阿里云密码或访问令牌
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Free up disk space
      run: |
        echo "Before cleanup:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        echo "After cleanup:"
        df -h

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Use temporary directory
      run: export TMPDIR=/tmp


        
    - name: Build and push Docker images
      run: |
          #image_name="registry.cn-hangzhou.aliyuncs.com/sync_dockerhub/$service:latest"
          # 构建和推送
          docker login -u ${{ secrets.ALIYUN_USERNAME }}  -p ${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker compose build
          docker compose push
